name: Get PR Number and Files with API
on:
  pull_request:
    branches:
      - main

jobs:
  get-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number and Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "Số PR: $PR_NUMBER"
          # Gọi API để lấy danh sách tệp
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files?per_page=100" | \
            jq -r '.[].filename | split("/") | .[:-1] | join("/")' | \
            sort | uniq > changed_dirs.txt
          echo "Các thư mục bị thay đổi:"
          cat changed_dirs.txt
